
#ifndef PROJET_CONFIG_H
#define PROJET_CONFIG_H

//CONFIGURATION DES TEMPS DE COURSE
#define TEMPS5400       //TEMPS (1H30)


//CONFIGURATION DE LA COURSE
#define NBRVOITURE 20       // NOMBRE MAX DE VOITURE
#define FINALTOURS 45       //NOMBRE DE TOUR DE LA FINAL
#define DELAY 1             //DELAI D'AFFICHAGE DES TOURS

//PARAMETRE DE MARGE
#define MAXTIMECOURSE 40000 //TEMPS MAX D'UN TOUR
#define MINTIMECOURSE 25000 //TEMPS MIN D'UN TOUR
#define MINSTANDTIME 5000   //TEMPS MINIMUM D'UN ARRET AU STAND
#define MAXSTANDTIME 10000  //TEMPS MAXIMUM D'UN ARRET AU STAND

//PROBABILITÉ
#define PROBACRACH 250      //PROBABILITÉ DE CRASHE
#define PROBASTAND 35       //PROBABILITÉ D'UN ARRET AU STAND


#endif //PROJET_CONFIG_H
