#ifndef PROJET_CONST
#define PROJET_CONST


#define TEMPS_P 3600000       //TEMPS POUR P1 (1H)
#define TEMPS_Q1 1080000      //TEMPS POUR Q1 (18 Minutes)
#define TEMPS_Q2 900000        //TEMPS POUR Q2 (15 Minutes)
#define TEMPS_Q3 720000        //TEMPS POUR Q3 (12 Minutes)


#define NBRVOITURE 20       // NOMBRE MAX DE VOITURE
#define TOURDEFINAL 10       //NOMBRE DE TOUR DE LA FINAL



#define MAXTIMECOURSE 40000 //TEMPS MAX D'UN TOUR
#define MINTIMECOURSE 25000 //TEMPS MIN D'UN TOUR
#define MINSTANDTIME 5000   //TEMPS MINIMUM D'UN ARRET AU STAND
#define MAXSTANDTIME 10000  //TEMPS MAXIMUM D'UN ARRET AU STAND


#define PROBACRACH 300    //PROBABILITÉ DE CRASHE
#define PROBASTAND 35    //PROBABILITÉ D'UN ARRET AU STAND


#endif 
